
[[constraint]]
  name = "github.com/ecnepsnai/ds"
  version = "1.1.21"

[[constraint]]
  name = "github.com/ecnepsnai/discord"
  version = "1.0.1"

[[constraint]]
  name = "github.com/ecnepsnai/limits"
  version = "1.0.0"

[[constraint]]
  name = "github.com/ecnepsnai/logtic"
  version = "1.3.1"

[[constraint]]
  name = "github.com/ecnepsnai/scheduler"
  version = "1.1.3"

[[constraint]]
  name = "github.com/ecnepsnai/store"
  version = "1.0.5"

[[constraint]]
  name = "github.com/ecnepsnai/web"
  version = "1.3.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/matoous/go-nanoid"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
